import os
import logging
from datetime import datetime
from typing import List
from .models import ResearchInsight

logger = logging.getLogger(__name__)

def synthesize_report(query: str, insights: List[ResearchInsight]) -> str:
    """
    Synthesizes discrete insights into a cohesive markdown report.
    Includes visual evidence (screenshots) and citations.
    """
    logger.info("🧠 Synthesizing final report...")
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    report = f"# Deep Research Report: {query}\n\n"
    report += f"**Date:** {timestamp}\n"
    report += f"**Sources Analyzed:** {len(insights)}\n"
    report += f"**Generated by:** Deep Research Agent v2.0 (Production-Grade)\n\n"
    
    report += "## 1. Executive Summary\n"
    if insights:
        combined_summary = " ".join([i.summary for i in insights[:3]])
        report += f"{combined_summary[:500]}...\n\n"
    else:
        report += "No insights available.\n\n"
    
    report += "## 2. Key Technical Findings\n"
    all_findings = []
    for insight in insights:
        for finding in insight.key_findings:
            all_findings.append(f"- {finding}")
    
    unique_findings = list(set(all_findings))
    report += "\n".join(unique_findings) + "\n\n"
    
    report += "## 3. Detailed Analysis & Evidence\n"
    for i, insight in enumerate(insights, 1):
        report += f"### Source {i}: {insight.title}\n"
        report += f"**URL:** [{insight.source_url}]({insight.source_url})\n\n"
        report += f"**Summary:** {insight.summary}\n\n"
        
        # Include screenshot if available
        if insight.screenshot_path and os.path.exists(insight.screenshot_path):
            report += f"**Visual Evidence:**\n"
            # Use relative path for markdown if possible, or absolute
            # For local viewing, absolute or relative to report file works.
            # Assuming report is in output_dir, and screenshots in output_dir/screenshots
            rel_path = os.path.relpath(insight.screenshot_path, os.path.dirname(insight.screenshot_path) + "/..")
            report += f"![Screenshot]({rel_path})\n\n"
        
        if insight.relevant_quotes:
            report += "**Relevant Quotes:**\n"
            for quote in insight.relevant_quotes:
                report += f"> \"{quote}\"\n"
            report += "\n"
        
        # Include source links for depth-2 exploration
        if insight.source_links:
            report += "**Related Sources Found on Page:**\n"
            for link in insight.source_links[:3]:
                if link.startswith('http'):
                    report += f"- [{link[:60]}...]({link})\n"
            report += "\n"
        
        report += "\n---\n\n"
    
    report += "## 4. References & Citations\n"
    report += "| # | Source | URL |\n"
    report += "|---|--------|-----|\n"
    for i, insight in enumerate(insights, 1):
        report += f"| {i} | {insight.title[:50]} | [{insight.source_url[:40]}...]({insight.source_url}) |\n"
    
    report += "\n---\n\n"
    report += "*Generated by Deep Research Agent - Advanced Web Intelligence System*\n"
    
    return report
