"""
Medical AI API Routes.

FastAPI routes for MedGemma AI services including entity extraction,
summarization, and terminology normalization.
"""

from typing import Optional, List, Dict, Any
from datetime import datetime
from fastapi import APIRouter, Query
from pydantic import BaseModel, Field
import logging

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/medical-ai", tags=["Medical AI"])


# ==================== Request/Response Models ====================


class EntityExtractionRequest(BaseModel):
    """Request for medical entity extraction."""

    text: str = Field(..., description="Medical text to extract entities from")
    document_type: Optional[str] = Field(None, description="Document type hint")
    include_confidence: bool = Field(True, description="Include confidence scores")

    class Config:
        json_schema_extra = {
            "example": {
                "text": "Patient John Smith, DOB 1985-03-15. Diagnosed with Type 2 Diabetes. Current medications: Metformin 500mg twice daily.",
                "document_type": "clinical_notes",
                "include_confidence": True,
            }
        }


class MedicalEntity(BaseModel):
    """Extracted medical entity."""

    entity_type: str  # medication, condition, lab_value, etc.
    value: str
    normalized_value: Optional[str] = None
    confidence: float
    start_pos: Optional[int] = None
    end_pos: Optional[int] = None
    context: Optional[str] = None


class EntityExtractionResponse(BaseModel):
    """Response for entity extraction."""

    entities: List[MedicalEntity]
    entity_count: int
    model_used: str
    processing_time_ms: float

    # Always include disclaimer per medical.md
    disclaimer: str = (
        "⚠️ AI-extracted entities are for informational purposes only. "
        "Not a substitute for professional medical review. "
        "Please verify with your healthcare provider."
    )


class PatientSummaryRequest(BaseModel):
    """Request for patient summary generation."""

    patient_id: str
    document_texts: List[str] = Field(
        ..., description="List of document texts to summarize"
    )
    include_recommendations: bool = Field(
        False, description="Include AI recommendations"
    )
    max_length: int = Field(500, description="Maximum summary length")

    class Config:
        json_schema_extra = {
            "example": {
                "patient_id": "patient123",
                "document_texts": [
                    "Lab results show elevated glucose at 126 mg/dL",
                    "Prescription: Metformin 500mg twice daily",
                ],
                "include_recommendations": False,
                "max_length": 500,
            }
        }


class PatientSummaryResponse(BaseModel):
    """Generated patient summary."""

    patient_id: str
    summary: str
    key_findings: List[str]
    conditions: List[str]
    medications: List[str]
    recent_labs: List[Dict[str, Any]]
    generated_at: datetime
    model_used: str

    # Mandatory disclaimer
    disclaimer: str = (
        "⚠️ This summary is generated by AI for informational purposes only. "
        "It is NOT a substitute for professional medical advice, diagnosis, or treatment. "
        "Always consult your healthcare provider for medical decisions."
    )


class TerminologyRequest(BaseModel):
    """Request for medical terminology expansion."""

    terms: List[str] = Field(
        ..., description="Medical terms or abbreviations to expand"
    )
    include_definitions: bool = Field(True, description="Include full definitions")

    class Config:
        json_schema_extra = {
            "example": {
                "terms": ["BP", "HbA1c", "CBC", "NPO"],
                "include_definitions": True,
            }
        }


class TermMapping(BaseModel):
    """Medical term mapping."""

    abbreviation: str
    full_form: str
    definition: Optional[str] = None
    category: Optional[str] = None


class TerminologyResponse(BaseModel):
    """Response for terminology expansion."""

    mappings: List[TermMapping]
    unknown_terms: List[str]


class MultimodalAnalysisRequest(BaseModel):
    """Request for multimodal (image + text) analysis."""

    document_id: str
    image_base64: Optional[str] = None
    extracted_text: Optional[str] = None
    analysis_type: str = Field("general", description="Type of analysis")


class MultimodalAnalysisResponse(BaseModel):
    """Response for multimodal analysis."""

    document_id: str
    image_analysis: Dict[str, Any]
    text_analysis: Dict[str, Any]
    combined_entities: List[MedicalEntity]
    quality_assessment: Dict[str, Any]
    processing_time_ms: float

    disclaimer: str = (
        "⚠️ AI analysis is for informational purposes only. "
        "Results require professional medical verification."
    )


# ==================== Routes ====================


@router.post(
    "/extract-entities",
    response_model=EntityExtractionResponse,
    summary="Extract Medical Entities",
    description="Extract medical entities (conditions, medications, lab values) from text using AI.",
)
async def extract_entities(
    request: EntityExtractionRequest, user_id: str = Query(..., description="User ID")
):
    """
    Extract medical entities from text using MedGemma AI.

    Entity types extracted:
    - **medications**: Drug names, dosages, frequencies
    - **conditions**: Diagnoses, symptoms
    - **lab_values**: Test results with units
    - **procedures**: Medical procedures
    - **anatomical**: Body parts mentioned
    - **temporal**: Dates and time references
    """
    import time

    start = time.time()

    # Mock extraction (in production: use MedGemma service)
    entities = [
        MedicalEntity(
            entity_type="patient_name",
            value="John Smith",
            confidence=0.98,
            start_pos=8,
            end_pos=18,
        ),
        MedicalEntity(
            entity_type="condition",
            value="Type 2 Diabetes",
            normalized_value="E11 - Type 2 diabetes mellitus",
            confidence=0.95,
            context="Diagnosed with Type 2 Diabetes",
        ),
        MedicalEntity(
            entity_type="medication",
            value="Metformin 500mg twice daily",
            normalized_value="Metformin 500mg BID",
            confidence=0.92,
        ),
    ]

    processing_time = (time.time() - start) * 1000

    return EntityExtractionResponse(
        entities=entities,
        entity_count=len(entities),
        model_used="medgemma",
        processing_time_ms=processing_time + 100,  # Add simulated model time
    )


@router.post(
    "/patient-summary",
    response_model=PatientSummaryResponse,
    summary="Generate Patient Summary",
    description="Generate an AI-powered summary of patient documents.",
)
async def generate_patient_summary(
    request: PatientSummaryRequest, user_id: str = Query(..., description="User ID")
):
    """
    Generate a comprehensive patient summary from multiple documents.

    The summary includes:
    - Key medical findings
    - Active conditions
    - Current medications
    - Recent lab results

    **Important**: This summary is AI-generated and requires professional review.
    """
    # Mock summary generation
    return PatientSummaryResponse(
        patient_id=request.patient_id,
        summary=(
            "Patient presents with Type 2 Diabetes, currently managed with Metformin. "
            "Recent lab work shows elevated glucose levels (126 mg/dL). "
            "Medication compliance reported as good. "
            "Recommend follow-up HbA1c testing in 3 months."
        ),
        key_findings=[
            "Elevated fasting glucose (126 mg/dL)",
            "Type 2 Diabetes diagnosis",
            "Current Metformin therapy",
        ],
        conditions=["Type 2 Diabetes Mellitus (E11)"],
        medications=["Metformin 500mg BID"],
        recent_labs=[
            {
                "test": "Glucose, Fasting",
                "value": "126",
                "unit": "mg/dL",
                "reference_range": "70-100",
                "status": "High",
            }
        ],
        generated_at=datetime.utcnow(),
        model_used="medgemma",
    )


@router.post(
    "/terminology/expand",
    response_model=TerminologyResponse,
    summary="Expand Medical Terminology",
    description="Expand medical abbreviations and provide definitions.",
)
async def expand_terminology(
    request: TerminologyRequest, user_id: str = Query(..., description="User ID")
):
    """
    Expand medical abbreviations and provide definitions.

    Useful for:
    - Understanding medical reports
    - Patient education
    - Document preprocessing
    """
    # In production: use MedicalTerminologyNormalizer
    known_mappings = {
        "BP": ("Blood Pressure", "The force of blood pushing against artery walls"),
        "HbA1c": ("Hemoglobin A1c", "Average blood sugar over 2-3 months"),
        "CBC": ("Complete Blood Count", "Panel measuring blood cell levels"),
        "NPO": ("Nothing by Mouth", "Patient should not eat or drink"),
        "PRN": ("As Needed", "Medication taken when necessary"),
        "BID": ("Twice Daily", "Take medication two times per day"),
        "TID": ("Three Times Daily", "Take medication three times per day"),
        "QID": ("Four Times Daily", "Take medication four times per day"),
    }

    mappings = []
    unknown = []

    for term in request.terms:
        term_upper = term.upper()
        if term_upper in known_mappings:
            full_form, definition = known_mappings[term_upper]
            mappings.append(
                TermMapping(
                    abbreviation=term,
                    full_form=full_form,
                    definition=definition if request.include_definitions else None,
                    category="medical",
                )
            )
        else:
            unknown.append(term)

    return TerminologyResponse(mappings=mappings, unknown_terms=unknown)


@router.post(
    "/multimodal/analyze",
    response_model=MultimodalAnalysisResponse,
    summary="Multimodal Document Analysis",
    description="Analyze medical documents using both image and text analysis.",
)
async def analyze_multimodal(
    request: MultimodalAnalysisRequest, user_id: str = Query(..., description="User ID")
):
    """
    Perform multimodal analysis on medical documents.

    Combines:
    - Visual analysis of document images
    - Text extraction and entity recognition
    - Quality assessment

    Best for scanned documents where OCR quality varies.
    """
    import time

    start = time.time()

    # Mock multimodal analysis
    result = MultimodalAnalysisResponse(
        document_id=request.document_id,
        image_analysis={
            "document_type_detected": "lab_report",
            "orientation": "portrait",
            "quality_score": 0.85,
            "has_tables": True,
            "has_handwriting": False,
        },
        text_analysis={
            "language": "en",
            "sections_detected": ["header", "patient_info", "results", "footer"],
            "confidence": 0.88,
        },
        combined_entities=[
            MedicalEntity(
                entity_type="lab_value", value="Glucose: 126 mg/dL", confidence=0.90
            )
        ],
        quality_assessment={
            "overall_quality": "good",
            "readability_score": 0.85,
            "completeness": 0.92,
            "issues": [],
        },
        processing_time_ms=(time.time() - start) * 1000 + 500,
    )

    return result


@router.get(
    "/models",
    summary="List Available Models",
    description="Get list of available AI models and their capabilities.",
)
async def list_models():
    """List available AI models."""
    return {
        "models": [
            {
                "id": "medgemma",
                "name": "MedGemma",
                "version": "1.0",
                "capabilities": [
                    "entity_extraction",
                    "summarization",
                    "terminology_normalization",
                ],
                "languages": ["en"],
                "status": "active",
            },
            {
                "id": "medgemma-multimodal",
                "name": "MedGemma Multimodal",
                "version": "1.0",
                "capabilities": [
                    "image_analysis",
                    "ocr_enhancement",
                    "visual_entity_extraction",
                ],
                "status": "active",
            },
        ]
    }


@router.get(
    "/health",
    summary="AI Service Health Check",
    description="Check health of AI services.",
)
async def health_check():
    """Health check for AI services."""
    return {
        "status": "healthy",
        "services": {
            "medgemma": "available",
            "terminology_service": "available",
            "multimodal_processor": "available",
        },
        "timestamp": datetime.utcnow().isoformat(),
    }
